# Generated by Django 3.0.5 on 2020-04-13 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('picture_url', models.CharField(max_length=256)),
                ('family_role', models.CharField(max_length=64)),
                ('sex', models.IntegerField()),
                ('phone_number', models.CharField(max_length=16)),
                ('dob_month', models.CharField(max_length=16)),
                ('dob_day', models.IntegerField()),
                ('dob_year', models.IntegerField()),
                ('email', models.CharField(max_length=64)),
                ('grade_level', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Family')),
            ],
        ),
    ]
