# Generated by Django 3.0.5 on 2020-04-13 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('adults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_adult', models.BooleanField()),
                ('title', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adult_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adults.Adult')),
                ('child_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='children.Child')),
            ],
        ),
    ]
